services:
  code:
    image: "web_service:latest"
    build:
      context: .
      dockerfile: Dockerfile
#    network_mode: host
    ports:
      - "8000:8000"
    volumes:
      - ./data:/code/data