version: "3.7"

networks:
  realtime_network:

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres:11
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - realtime_network

  realtime_parser:
    container_name: realtime_parser
    image: "terysy/realtime_parser:latest"
    build:
      context: .
      dockerfile: parser/Dockerfile
    volumes:
      - ./tg_session/session_name.session:/code/session_name.session
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    networks:
      - realtime_network


  realtime_web:
    container_name: realtime_web
    image: "terysy/realtime_web:latest"
    build:
      context: .
      dockerfile: web_service/Dockerfile
    ports:
      - "80:8000"
    volumes:
      - ./data:/code/data
      - ./migrations:/code/db_lib/alembic/versions
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    networks:
      - realtime_network
