name: MAIN - build and deploy web_service and parser

on:
  push:
    branches:
      - 'main'

jobs:
  docker-web:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO_WEB }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }}
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build web_service Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish web_service Docker image
        run: docker push $REPO

  redeploy-web:
    name: Redeploy web webhook call
    runs-on: ubuntu-18.04
    needs: [docker-web]
    steps:
      - name: Deploy docker container webhook for web_service
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL_WEB  }}


  docker-parser:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO_PARSER }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }}
          -p ${{ secrets.DOCKER_PASS }}
      - name: Build parser Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} -f parser/Dockerfile .
      - name: Publish parser Docker image
        run: docker push $REPO

  redeploy-parser:
    name: Redeploy parser webhook call
    runs-on: ubuntu-18.04
    needs: [ docker-parser]
    steps:
      - name: Deploy docker container webhook for parser
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL_PARSER  }}