name: MAIN - build and deploy web_service and parser

on:
  push:
    branches:
      - 'main'

jobs:
  docker-web:
    name: Publish web - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO_WEB }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }}
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build web_service Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} -f web_service/Dockerfile .
      - name: Publish web_service Docker image
        run: docker push --all-tags $REPO

  docker-parser:
    name: Publish parser - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO_PARSER }}
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }}
          -p ${{ secrets.DOCKER_PASS }}
      - name: Build parser Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} -f parser/Dockerfile .
      - name: Publish parser Docker image
        run: docker push --all-tags $REPO

  redeploy-parser:
    name: Redeploy ml_jobs webhook call
    runs-on: ubuntu-18.04
    needs: [docker-web, docker-parser ]
    steps:
      - name: Deploy all docker containers webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL_ALL}}
